name: 'Make sure all tests run and that firmware can be built on push'
run-name: ${{ github.actor }} initiated a push request

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  call_chk_devcontainer:
    name: Checking for valid dev container image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/chk_devcontainer_img.yml
    with:
      image-id: iot-base-img:latest
    secrets:
      secr-token: ${{ secrets.GITHUB_TOKEN }}

  run_tests:
    runs-on: ubuntu-latest
    needs: call_chk_devcontainer
    permissions:
      contents: write
    env:
      IMAGE_NAME: ${{ needs.call_chk_devcontainer.outputs.image-path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Pull dev container
        run: docker pull ${IMAGE_NAME}
      - name: Run tests inside container
        run: |
          docker run --rm \
            --mount type=bind,src=${{ github.workspace }},dst=/workspaces \
            --mount type=bind,src=$HOME,dst=/root \
            ${IMAGE_NAME} sh -c "cd /workspaces;./pipeline/config_build_run_test.sh"
      - name: Build target firmware inside container
        run: |
          docker run --rm \
            --mount type=bind,src=${{ github.workspace }},dst=/workspaces \
            --mount type=bind,src=$HOME,dst=/root \
            ${IMAGE_NAME} sh -c "cd /workspaces;./pipeline/build_firmware_files.sh"      
